In [1]:
# importing all necessary libraries
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# reading the dataset
data = pd.read_csv('data.csv')
data.shape

(18207, 89)

In [3]:
# lets also check the columns in the data
data.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes', 'Release Clause'],
      dtype='object')

### Find the Most Expensive Players whose contracts are going to Expire Soon

In [5]:
x

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
5,5,183277,E. Hazard,27,https://cdn.sofifa.org/players/4/19/183277.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,91,Chelsea,...,91.0,34.0,27.0,22.0,11.0,12.0,6.0,8.0,8.0,€172.1M
6,6,177003,L. Modrić,32,https://cdn.sofifa.org/players/4/19/177003.png,Croatia,https://cdn.sofifa.org/flags/10.png,91,91,Real Madrid,...,84.0,60.0,76.0,73.0,13.0,9.0,7.0,14.0,9.0,€137.4M
8,8,155862,Sergio Ramos,32,https://cdn.sofifa.org/players/4/19/155862.png,Spain,https://cdn.sofifa.org/flags/45.png,91,91,Real Madrid,...,82.0,87.0,92.0,91.0,11.0,8.0,9.0,7.0,11.0,€104.6M
13,13,168542,David Silva,32,https://cdn.sofifa.org/players/4/19/168542.png,Spain,https://cdn.sofifa.org/flags/45.png,90,90,Manchester City,...,93.0,59.0,53.0,29.0,6.0,15.0,7.0,6.0,12.0,€111M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18166,18166,243621,N. Ayéva,16,https://cdn.sofifa.org/players/4/19/243621.png,Sweden,https://cdn.sofifa.org/flags/46.png,48,72,Örebro SK,...,44.0,14.0,19.0,16.0,10.0,9.0,8.0,7.0,6.0,€158K
18179,18179,246243,J. Williams,17,https://cdn.sofifa.org/players/4/19/246243.png,England,https://cdn.sofifa.org/flags/14.png,48,64,Northampton Town,...,37.0,42.0,51.0,49.0,14.0,11.0,7.0,11.0,8.0,€119K
18187,18187,240158,C. Ehlich,19,https://cdn.sofifa.org/players/4/19/240158.png,Germany,https://cdn.sofifa.org/flags/21.png,47,59,SpVgg Unterhaching,...,47.0,40.0,42.0,42.0,13.0,12.0,11.0,15.0,12.0,€66K
18189,18189,240160,A. Kaltner,18,https://cdn.sofifa.org/players/4/19/240160.png,Germany,https://cdn.sofifa.org/flags/21.png,47,61,SpVgg Unterhaching,...,37.0,28.0,15.0,22.0,15.0,5.0,14.0,12.0,8.0,€125K
18203,18203,243165,N. Christoffersson,19,https://cdn.sofifa.org/players/4/19/243165.png,Sweden,https://cdn.sofifa.org/flags/46.png,47,63,Trelleborgs FF,...,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,€113K

In [4]:
import warnings
warnings.filterwarnings('ignore')

# we have to filter players whose contracts are going to be valid till 2020 only.
x = data[data['Contract Valid Until'] == "2020"]

# defining a function for cleaning the wage column
def extract_value_from(column):
    out = column.replace('€', '')
    if 'M' in out:
        out = float(out.replace('M', ''))*1000000
    elif 'K' in column:
        out = float(out.replace('K', ''))*1000
    return float(out)

# applying the function to the wage column so that we can sort the highest paid footballers
x['Wage'] = x['Wage'].apply(extract_value_from)

# Now we have to sort those players who are highest paid
x[['Name','Nationality','Club','Age', 'Wage']].sort_values(by = 'Wage', ascending = False).head(10)

            Name Nationality                 Club  Age      Wage
6      L. Modrić     Croatia          Real Madrid   32  420000.0
8   Sergio Ramos       Spain          Real Madrid   32  380000.0
5      E. Hazard     Belgium              Chelsea   27  340000.0
13   David Silva       Spain      Manchester City   32  285000.0
3         De Gea       Spain    Manchester United   27  260000.0
49    Jordi Alba       Spain         FC Barcelona   29  250000.0
24  G. Chiellini       Italy             Juventus   33  215000.0
31    C. Eriksen     Denmark    Tottenham Hotspur   26  205000.0
21     E. Cavani     Uruguay  Paris Saint-Germain   31  200000.0
46      K. Navas  Costa Rica          Real Madrid   31  195000.0

### Make a Function to Generate a Report for Players

In [6]:
def report(player):
    return data[data['Name'] == player][['Nationality','Club',
                                         'Overall','Potential',
                                         'Contract Valid Until','Wage',
                                        'International Reputation']].reset_index(drop = True).T

report('L. Messi')

                                     0
Nationality                  Argentina
Club                      FC Barcelona
Overall                             94
Potential                           94
Contract Valid Until              2021
Wage                             €565K
International Reputation             5

### Compare Indian Footballers with Russian Footballers

In [11]:
x

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
276,276,193525,Mário Fernandes,27,https://cdn.sofifa.org/players/4/19/193525.png,Russia,https://cdn.sofifa.org/flags/40.png,82,82,PFC CSKA Moscow,...,76.0,83.0,82.0,84.0,12.0,13.0,14.0,13.0,12.0,€40.7M
381,381,187491,F. Smolov,28,https://cdn.sofifa.org/players/4/19/187491.png,Russia,https://cdn.sofifa.org/flags/40.png,81,81,Lokomotiv Moscow,...,73.0,26.0,28.0,24.0,16.0,9.0,16.0,15.0,10.0,€38.9M
541,541,148119,I. Akinfeev,32,https://cdn.sofifa.org/players/4/19/148119.png,Russia,https://cdn.sofifa.org/flags/40.png,80,80,PFC CSKA Moscow,...,67.0,18.0,13.0,13.0,77.0,72.0,78.0,82.0,84.0,€18.7M
542,542,147782,I. Denisov,34,https://cdn.sofifa.org/players/4/19/147782.png,Russia,https://cdn.sofifa.org/flags/40.png,80,80,Lokomotiv Moscow,...,77.0,81.0,81.0,73.0,13.0,7.0,15.0,13.0,12.0,€9.4M
568,568,229909,A. Lunev,26,https://cdn.sofifa.org/players/4/19/229909.png,Russia,https://cdn.sofifa.org/flags/40.png,79,81,NaN,...,69.0,18.0,20.0,12.0,80.0,73.0,65.0,77.0,85.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17129,17129,228198,J. Singh,26,https://cdn.sofifa.org/players/4/19/228198.png,India,https://cdn.sofifa.org/flags/159.png,55,58,NaN,...,42.0,26.0,18.0,13.0,15.0,14.0,8.0,10.0,16.0,NaN
17197,17197,245164,V. Kaith,21,https://cdn.sofifa.org/players/4/19/245164.png,India,https://cdn.sofifa.org/flags/159.png,55,64,NaN,...,29.0,8.0,12.0,11.0,55.0,50.0,57.0,59.0,53.0,NaN
17339,17339,233526,S. Passi,23,https://cdn.sofifa.org/players/4/19/233526.png,India,https://cdn.sofifa.org/flags/159.png,54,63,NaN,...,45.0,14.0,23.0,21.0,8.0,6.0,13.0,9.0,10.0,NaN
17436,17436,236452,D. Lalhlimpuia,20,https://cdn.sofifa.org/players/4/19/236452.png,India,https://cdn.sofifa.org/flags/159.png,54,67,NaN,...,46.0,26.0,17.0,13.0,7.0,8.0,12.0,11.0,11.0,NaN
17539,17539,234508,C. Singh,21,https://cdn.sofifa.org/players/4/19/234508.png,India,https://cdn.sofifa.org/flags/159.png,53,62,NaN,...,41.0,56.0,49.0,53.0,12.0,9.0,6.0,14.0,8.0,NaN

In [10]:
# lets first filter all the Russian and Indian Footballers
x = data[(data['Nationality'] == 'Russia') | (data['Nationality'] == 'India')]

# now let's group this datasets based on nationality and aggregate on Potential and Overall Scores
x[['Nationality','Overall','Potential']].groupby(['Nationality']).agg('mean').style.background_gradient(cmap = 'copper')

### Find the Most Popular Footballers under 20

In [13]:
# lets first filter all the under 20 players and then sort with their Values

x = data[data['Age'] < 20]

# defining a function for cleaning the wage column
def extract_value_from(column):
    out = column.replace('€', '')
    if 'M' in out:
        out = float(out.replace('M', ''))*1000000
    elif 'K' in column:
        out = float(out.replace('K', ''))*1000
    return float(out)

# applying the function to the wage column so that we can sort the highest paid footballers
x['Value'] = x['Value'].apply(extract_value_from)

x[['Name','Age','Value','Overall']].sort_values(by = 'Value', ascending = True).head(10).style.background_gradient(cmap = 'copper')